version: "3.7"

services:
  docker-app:
    image: ajeetkhan/docker-app:dinddemo
    build: .
    privileged: true
    ports:
      - "5000:5000"
    volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
  
  dind:
    image: jpetazzo/dind
    privileged: true
    volumes:
      - /etc/apparmor.d:/etc/apparmor.d:rw
      - /sys/kernel/security:/sys/kernel/security:rw
    ports:
      - "1234"
    environment:
      - PORT=1234
    cap_add:
      - ALL
    command: >      
        /bin/bash -c "cd /usr/local/bin/ && nohup wrapdocker & `docker run -t --security-opt 'apparmor=custom' -v /sys/kernel/security:/sys/kernel/security nginx`"
