version: "2.3"

services:
  docker-app:
    image: ajeetkhan/docker-app:stackdemo
    build: .
    privileged: true
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  dind:
    image: jpetazzo/dind
    privileged: true
    security_opt:
      - apparmor:custom-profile
    volumes:
      - /etc/apparmor.d:/etc/apparmor.d
      - /sys/kernel/security:/sys/kernel/security
    ports:
      - "1234"
    environment:
      - PORT=1234
    