version: "2.3"

services:
  docker-app:
    image: ajeetkhan/docker-app:stackdemo
    build: .
    privileged: true
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  dind:
    image: ubuntu
    privileged: true
    runtime: sysbox-runc
    volumes:
      - /home/ajeet/apparmor:/etc/apparmor.d/containers/