version: "3.9"

services:
  docker-app:
    image: ajeetkhan/docker-app:stackdemo
    build: .
    privileged: true
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  dind:
    #image: docker:dind
    image: ajeetkhan/dind-ubuntu-20.04
    privileged: true
    volumes:
      - ./apparmor:/etc/apparmor.d/containers/